### ISSUE TITLE
add naas logo to jupyter upper left corner

### ISSUE THREAD

**Issue by BobCashStory** [jupyter-naas/singleuser#3]

**Comment by jravenel** [comment]
<img width="96" alt="favicon" src="https://user-images.githubusercontent.com/21052349/94674594-b5418300-0318-11eb-8710-a6fe6fe3f017.png">

**Comment by jravenel** [comment]
@navinkarkera just added this guys here. 
please also change the title and favicon of the tab (see image) 

<img width="1649" alt="Capture d’écran 2020-09-30 à 12 16 10" src="https://user-images.githubusercontent.com/21052349/94674692-dace8c80-0318-11eb-9a4b-cdea659f9f7c.png">

**Comment by BobCashStory** [comment]
Done ✅
